version: "3.8"

services:
  postgres:
      build: 
        context: ./docker/postgresql
        args:
          - POSTGRES_VERSION=${POSTGRES_VERSION}
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        # - PGDATA=/pgdata
        - POSTGRES_DB=${POSTGRES_DB}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U daniel -d homework"]
        interval: 5s
        timeout: 5s
        retries: 5
  api:
      build:
        context: ./
        dockerfile:  ./docker/golang/Dockerfile
        args:
          - GOLANG_VERSION=${GOLANG_VERSION}
      ports:
        - "8080:8080"
        - "${GRPC_PORT}:${GRPC_PORT}"
      depends_on:
        postgres:
          condition: service_healthy
  workspace: 
      build:
        context: ./docker/workspace
        args:
          - GOLANG_VERSION=${GOLANG_VERSION}
      volumes:
        - ./:/app
      ports:
        - "8080:8080"
        - "${GRPC_PORT}:${GRPC_PORT}"
      depends_on:
        postgres:
          condition: service_healthy
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - '${REDIS_PORT}:${REDIS_PORT}'
#    stdin_open: true
#    tty: true
#    command: redis-server  --requirepass ${REDIS_PASSWORD}
volumes:
    db-data:
