// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: article.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	// GetArticlesPage: get user articles page
	GetArticlesPage(ctx context.Context, in *GetArticlesPageReq, opts ...grpc.CallOption) (*GetArticlesPageRes, error)
	// setArticlesPage: set user articles page
	UpdateArticlesPage(ctx context.Context, in *UpdateArticlesPageReq, opts ...grpc.CallOption) (*UpdateArticlesPageRes, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetArticlesPage(ctx context.Context, in *GetArticlesPageReq, opts ...grpc.CallOption) (*GetArticlesPageRes, error) {
	out := new(GetArticlesPageRes)
	err := c.cc.Invoke(ctx, "/proto.articleService/GetArticlesPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) UpdateArticlesPage(ctx context.Context, in *UpdateArticlesPageReq, opts ...grpc.CallOption) (*UpdateArticlesPageRes, error) {
	out := new(UpdateArticlesPageRes)
	err := c.cc.Invoke(ctx, "/proto.articleService/UpdateArticlesPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations should embed UnimplementedArticleServiceServer
// for forward compatibility
type ArticleServiceServer interface {
	// GetArticlesPage: get user articles page
	GetArticlesPage(context.Context, *GetArticlesPageReq) (*GetArticlesPageRes, error)
	// setArticlesPage: set user articles page
	UpdateArticlesPage(context.Context, *UpdateArticlesPageReq) (*UpdateArticlesPageRes, error)
}

// UnimplementedArticleServiceServer should be embedded to have forward compatible implementations.
type UnimplementedArticleServiceServer struct {
}

func (UnimplementedArticleServiceServer) GetArticlesPage(context.Context, *GetArticlesPageReq) (*GetArticlesPageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticlesPage not implemented")
}
func (UnimplementedArticleServiceServer) UpdateArticlesPage(context.Context, *UpdateArticlesPageReq) (*UpdateArticlesPageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArticlesPage not implemented")
}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_GetArticlesPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticlesPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticlesPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.articleService/GetArticlesPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticlesPage(ctx, req.(*GetArticlesPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_UpdateArticlesPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticlesPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).UpdateArticlesPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.articleService/UpdateArticlesPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).UpdateArticlesPage(ctx, req.(*UpdateArticlesPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.articleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticlesPage",
			Handler:    _ArticleService_GetArticlesPage_Handler,
		},
		{
			MethodName: "UpdateArticlesPage",
			Handler:    _ArticleService_UpdateArticlesPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
